# Generated by Django 5.2.7 on 2025-10-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
                ('quiz_scores', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
